### ISSUE TITLE
GLTFLoader error

### ISSUE THREAD

**Issue by noreo** [franky-adl/threejs-starter-template#1]
I tried to load GLTF file, however, I get this error, anyway I try: _SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data._ 
After looking around, it's looks like a server error, more than a treejs error, but I am not an expert couldn't find a way to it. 
here is the simplest code I tried, into initScene:
```
  const loader = new GLTFLoader();
loader.load( '.assets/earth_clean.gltf', function ( gltf ) {
	scene.add( gltf.scene );
} );
```
Note: I know my file is fine, it worked on older boilerplate I used.
Thanks :)

**Comment by franky-adl** [comment]
Hi there, thanks for trying my boilerplate. I think it's probably your path issue, it should be './assets/earth_clean.gltf', notice the '/' after the first dot.

**Comment by franky-adl** [comment]
If that still doesn't fix your issue, try to import it first
```
import Earth from './assets/earth_clean.gltf'
```
and then use the imported path variable directly when you load it:
```
const loader = new GLTFLoader();
loader.load( Earth, function ( gltf ) {
	scene.add( gltf.scene );
} );
```

**Comment by noreo** [comment]
thank you for your reply. 
I tried to change the patch (adding "/") but it didn't change. 
I tried import as well, but I think parcel doesn't know what a gltf is:
`import Earth from './assets/earth_clean.gltf'`
I get the error: 
`@parcel/core: No transformers found for _src/assets/model_water.glb_.`

**Comment by franky-adl** [comment]
Hmm, you're probably right. I recently also ran into the problem where I couldn't load .hdr image files via parcel and ended up putting the file up a 'CDN' of myself. Sorry about that, I'll probably look for a better bundler soon that has a wider compatibility for different file types.

**Comment by noreo** [comment]
Thanks, I'll wait for the update then :)

**Comment by franky-adl** [comment]
Hey, It's probably a bit late, but I found this workaround: https://stackoverflow.com/questions/70487267/parcel-core-no-transformers-found-for-glb-file

**Comment by franky-adl** [comment]
Fixed with this commit https://github.com/franky-adl/threejs-starter-template/commit/cc7f8a03b47cded51216dc1235971ec2dd8c193b
